keys:
  # Administrator Key "ssh-to-age -i ~/.ssh/id_ed25519.pub" (Decryption done with Portable SSH PrivateKey)
  - &admin age1c9plrjxglcrepqjujaz7kz46s05tlh33ztr6x5fe83gwuq0jzsxqdr527n

  # Connect to target host and run "ssh-keyscan targethost.local | ssh-to-age"
  # WARNING: These change per-install. If the OS is reinstalled, these must be reset.
  # - &siminet-01 age1...  # TODO: fill in when online
  - &siminet-02 age1zja04f7yzlj9uq4pe8sys98xyygfjq7nskdcr4vhjqqf6252k3zsta9qve
  - &siminet-03 age1r5u55x3t63dmqxclrmrcv0aa24h82e8vukxrpufpsnkqk3nf6egsajtcqp
  # - &siminet-04 age1...  # TODO: fill in when online

creation_rules:
  - path_regex: hosts/x86_64-servers/siminet-01/secrets/.*\.yaml$
    key_groups:
      - age: [*admin]

  - path_regex: hosts/x86_64-servers/siminet-02/secrets/.*\.yaml$
    key_groups:
      - age: [*admin]

  - path_regex: hosts/x86_64-servers/siminet-03/secrets/.*\.yaml$
    key_groups:
      - age: [*admin, *siminet-03]

  - path_regex: hosts/x86_64-servers/siminet-04/secrets/.*\.yaml$
    key_groups:
      - age: [*admin]
